import "./globals.css";
import { Providers } from "@/redux/provider";
import { FixedFooter, Header } from "@/components";
import { getLocalData } from "@/lib/localdata";
import { error } from "next/dist/build/output/log";

export const metadata = {
  title: "تماشای آنلاین فیلم و سریال | فیلیمو",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const data = await getLocalData();

  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="relative">
            <Header data={data} />
            {children}
            <FixedFooter />
          </div>
        </Providers>
      </body>
    </html>
  );
}
