import { Movie } from "@/components";

export const metadata = {
  title: "بهترین",
  description: "Generated by create next app",
};
const Movies = () => {
  return <Movie />;
};

export default Movies;
