import Movie from "@/components/movies/Movie";

export const metadata = {
  title: "بهترین",
  description: "Generated by create next app",
};
const Movies = () => {
  return <Movie />;
};

export default Movies;
